language: python
python:
  - '3.7'

#cache:
#  directories:
#    - $HOME/download
#    - $HOME/miniconda

#before_cache:
#    - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
#    - conda update -q conda
    - conda info -a

install:
  - git clone https://github.com/CCI-Tools/cate.git
  - cd cate
  - conda env create -f environment.yml;
  - conda init bash
  - source activate cate-env
  - conda list 
  - python setup.py install
#  - travis_retry pip install --upgrade pip
#  - travis_retry pip install requests
#  - travis_retry pip install pytest
#  - travis_retry pip install xarray
#  - travis_retry pip install jdcal
#  - travis_retry pip install matplotlib
#  - travis_retry pip install shapely
#  - travis_retry pip install geopandas
#  - travis_retry pip install pillow
#  - travis_retry conda install -c conda-forge cartopy -y
  - cd ..
script:
  - pytest -s --junitxml=ci/reports/`date +%F`.xml validation/python/test_data_support.py

