language: python
python:
  - '3.7'
before_install:
  - git clone https://github.com/CCI-Tools/cate.git
  - cd cate
  - conda env create
  - source activate cate-env
install:
  - python setup.py install
  - travis_retry pip install --upgrade pip
  - travis_retry pip install pytest
script:
  - cd ..
  - pytest -s --junitxml=ci/reports/`date +%F`.xml validation/python/test_data_support.py

